### DISCUSSION TITLE
Backup pvc with hostPath

### DISCUSSION THREAD

**Discussion by ParitoshBh** [backube/volsync#1180] [Q&A] [answered]
I am able to create and associate PersistentVolume with a pod. However, when I try to backup the pvc using VolSync, it doesn't work.

Here's how I have setup pv and pvc,

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-upload
  labels:
    app: immich-server
    parent: immich
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/k3s/storage"
```

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-upload-claim
  labels:
    app: immich-server
    parent: immich
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
```

and triggering manual volsync backup using,

```yaml
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
    name: immich-backup
spec:
    sourcePVC: immich-upload
    trigger:
        manual: manual-backup-id-1
    restic:
        repository: restic-nas-immich-config
        copyMethod: Direct
``` 

I can see that replicationsource gets registered but nothing happens.

Any idea as to what might be happening here?

**Comment by JohnStrunk** [comment, marked as answer]
What sticks out to me is that `spec.sourcePVC` needs to match the name of the PVC, not the PV.

If you need further help, please post the objects, including their `.status` fields.

**Reply by ParitoshBh** [reply]
Thank you for such a quick response!

I tried with `spec.sourcePVC: immich-upload-claim`,

```yaml
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
    name: immich-backup
spec:
    sourcePVC: immich-upload-claim
    trigger:
        manual: manual-backup-id-2
    restic:
        repository: restic-nas-immich-config
        copyMethod: Direct
```

The job did get registered but there was a warning (in Headlamp) along the lines of `ReadWriteMany` not supported. Changing `spec.accessModes` to `ReadWriteOnce` solved the issue and backup pod ran just fine.

Thanks a lot!
