### DISCUSSION TITLE
Backup a nextcloud instance

### DISCUSSION THREAD

**Discussion by s4ndalHat** [backube/volsync#1419] [Q&A]
Hello community,

Recently i have tested volsync for various use case for our internal tools running on Kubernetes clusters.
I have faced a problem when trying to backup a Nextcloud instance using volsync.

I have no CSI drive that can do snapshot on the cluster, so I used the copyMethod Direct mode.
But the volsync-src-data pod which take restic snapshot is running then **terminating** suddenly and **re-create itself numerous times**, and that makes the backup never success (it's been 15 hours running non-stop).

So, my bucket s3 was filled with numerous snapshots which is not completed...

Do you have any insight ?

Kubernetes version: 1.28
Volsync installed with helm chart 0.10.0
Data mover: restic copyMethod Direct

**Comment by tesshuflower** [comment]
@s4ndalHat hopefully it's possible to get a bit more information from the system or from the mover logs themselves to help narrow down what the issue is.

Some suggestions for things to try and capture:

- the `replicationsource` itself - are there errors being captured in the `.status`?
- logs from the volsync-src-data mover pod when it runs - any errors in there?
- From kubernetes, is there any information about the mover pods?  Are they getting killed due to OOM or anything like that?
- There should be a job (named something like volsync-src-data) created which is the one that's starting the mover pods - Can you look at the status of this job and run a `kubectl describe job <jobname>` on it?

**Comment by s4ndalHat** [comment]
Hello @tesshuflower,
So, I decided to activate unlock just to test if thats the problem, I'm getting this error :

![image](https://github.com/user-attachments/assets/2f21f97c-1b98-4591-ac5f-14b6a659b9cc)

I'm trying to reproduce the source issue

**Reply by s4ndalHat** [reply]
SO in the logs of the data mover, there is no current OOMKill, the pod is just killing itself during the copy, (I can't send lofs containing sensitive information) and as I look at my events, there is no "OOMKilled" status, only "Killing" directly ...

**Reply by tesshuflower** [reply]
I guess I don't want to speculate too much on how you got into this situation,  but sounds like perhaps some files in the bucket are perhaps encrypted with a key different from what is used in the config file?

I would think that running different backups to the same bucket/path would not overwrite/corrupt each other as they would need to use the same restic password?  The config would need to be deleted first somehow, then restic init would create a new one.  Maybe I'm missing something though.

If possible, it may be useful to run a test to a new backup location to see if you get a clean backup.

**Reply by s4ndalHat** [reply]
@tesshuflower ok, I'll look onto that, I will try a new repo path,

**Reply by s4ndalHat** [reply]
@tesshuflower I created a new repo for the backup, 
The volsync src-data pod still terminates at some time, making the backup running in indefinite loop. 

In my event, I do not have any OOMKilled status between Pod Ready and Terminating, ...
Is there a way where I can see why this happen ?

**Reply by tesshuflower** [reply]
Normally if kubernetes is the one killing the pod (such as due to resource issues like memory), you may see something in kubernetes, such as in the events of the pod itself when it's killed.  

Is there any indication from the pod log what is happening?

**Reply by s4ndalHat** [reply]
@tesshuflower while I'm using k9s to have an overview, during the backup process I looked at the logs of the job that take care of the backup.. but in the logs, the stream is just closed,

Looking at the events of my pods & kubernetes cluster, there is no OOMKill statemeent, only a "Normal Killing" state :(

**Reply by tesshuflower** [reply]
If you want to try debugging what is going on manually, you can take a look at this:

https://github.com/backube/volsync/issues/1415#issuecomment-2429687337

**Reply by s4ndalHat** [reply]
@tesshuflower hello,
So I tried to enter debug mode, this is the log of my pod:
![image](https://github.com/user-attachments/assets/20d4c6ac-590d-4da8-a255-81573db94479)

But as I said, the pod and specifically this one for this particular PVC which contains user data, 
the pod is killing himself after 1-2 min...

My replicationSource manifest:

```yaml
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: nc-agora01-data
  namespace: nc-agora01
  annotations:
    volsync.backube/enable-debug-mover: ""
spec:
  sourcePVC: nc-agora01-nextcloud-nextcloud-data
  trigger:
    schedule: "0 1 * * *"
  restic:
    storageClassName: "nc-test"
    pruneIntervalDays: 3
    repository: nc-agora01-data-repo
    retain:
      hourly: 1
      daily: 1
      weekly: 1
      monthly: 1
      yearly: 1
    unlock: triggerString
    copyMethod: Direct
```

In kubernetes events:

![image](https://github.com/user-attachments/assets/696bf5c9-9bb5-4436-b313-ca3a2bc5e0c2)
