### DISCUSSION TITLE
Best option to sync local-path PVs within multi-node k3s cluster?

### DISCUSSION THREAD

**Discussion by pschiffe** [backube/volsync#1550] [Q&A] [answered]
Hello, I have a multi node k3s cluster with Rancher's local-path volumes. I would like to distribute the content of some volumes to all nodes, but tools like Longhorn are overkill for me. Syncing the volumes, for example, once per day would be enough.

I found this tool, but not sure what would be the best option to choose. Is it possible to use Rclone replication without intermediate S3 storage? As I'm syncing just within the cluster. Also copyMethod direct is fine as well.

Or maybe Rsync replication (via TLS)? But I don't need TLS and I need 1 to many replication, not just 1 to 1. Syncthing seems to be too complex. ReplicationDestination Volume Populator feature also looks cool.

What would be the best way to proceed in my case? Thanks.

**Comment by tesshuflower** [comment]
Hi @pschiffe ,

It sounds like rclone would normally be a good pick for you, but does require some intermediate location to store the files.

The advantage is you can have 1 replicationsource to store the data and then run multiple replicationdestinations to pull the data down, to fan it out.

I haven't looked into all the available storage providers for rclone, but you could look at running something locally in your cluster (for example we use minio for our dev/testing which provides an s3 compatible store you can run within the cluster).

Another option is to use rsync - and we would recommend rsync-tls as this is the newer version of the mover that supports running unprivileged.  If you do use rsync you would need a 1-1 replicationsource-to-replicationdestination however.  Essentially you'd be pointing each replicationsource to a replicationdestination within your cluster, so you could use a clusterIP service type (this is the default) to do the communication locally.

Lastly, syncthing could still be an option, but would normally be something you keep running to keep files in sync live.  This would depend on your application itself and how you want to replicate the data.

**Comment by pschiffe** [comment, marked as answer]
Thank you for the overview. This is what I ended up with for small 3 node cluster to distribute mariadb backups from one to all nodes. For bigger clusters I'll probably use rclone.

```
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: flux-mariadb-backup-2
spec:
  trigger:
    schedule: "0 3 * * *"
  rsyncTLS:
    copyMethod: Direct
    capacity: 1Gi
    accessModes:
      - ReadWriteOnce
    storageClassName: local-path-retain
    moverSecurityContext:
      runAsUser: 999
      runAsGroup: 999
      fsGroup: 999
    moverAffinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-index
                  operator: In
                  values:
                    - "2"

---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: flux-mariadb-backup-3
spec:
  trigger:
    schedule: "0 3 * * *"
  rsyncTLS:
    copyMethod: Direct
    capacity: 1Gi
    accessModes:
      - ReadWriteOnce
    storageClassName: local-path-retain
    moverSecurityContext:
      runAsUser: 999
      runAsGroup: 999
      fsGroup: 999
    moverAffinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-index
                  operator: In
                  values:
                    - "3"

---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: flux-mariadb-backup-2
spec:
  sourcePVC: flux-mariadb-backup-1
  trigger:
    schedule: "5 3 * * *"
  rsyncTLS:
    keySecret: volsync-rsync-tls-flux-mariadb-backup-2
    address: volsync-rsync-tls-dst-flux-mariadb-backup-2
    copyMethod: Direct
    moverSecurityContext:
      runAsUser: 999
      runAsGroup: 999
      fsGroup: 999
    moverAffinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-index
                  operator: In
                  values:
                    - "1"

---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: flux-mariadb-backup-3
spec:
  sourcePVC: flux-mariadb-backup-1
  trigger:
    schedule: "25 3 * * *"
  rsyncTLS:
    keySecret: volsync-rsync-tls-flux-mariadb-backup-3
    address: volsync-rsync-tls-dst-flux-mariadb-backup-3
    copyMethod: Direct
    moverSecurityContext:
      runAsUser: 999
      runAsGroup: 999
      fsGroup: 999
    moverAffinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-index
                  operator: In
                  values:
                    - "1"
```
