### DISCUSSION TITLE
Is there a way to mark using labels ReplicationSources and ReplicationDestinations?

### DISCUSSION THREAD

**Discussion by Sanjeeth8733** [backube/volsync#1670] [Q&A]
Hi VolSync team,

For our internal use of VolSync, we occasionally need to turn off VolSync workers during cluster upgrades/downgrades. We're managing the VolSync Custom Resources (ReplicationSource and ReplicationDestination) manually, not via Helm, because of two key reasons:

These CRs need to be the very last things created by Kubernetes during install.

They need to be the first things removed during uninstall/upgrade.

To support this, we wanted to mark the resources in a way that makes them easy to select and delete via kubectl or scripts.

We tried adding labels like so:

```yaml
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: {{ $ownerName }}-{{ $mountIndex|toString }}
  namespace: {{ $releasenamespace }}
  labels:
    app.kubernetes.io/name: myInstanceName
    app.kubernetes.io/instance: myInstanceName
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "110"
spec:
  ...
  ```

But unfortunately, these labels are not present on the actual resource after creation. We couldn't find documentation on whether custom labels/annotations are allowed or filtered out by the controller.

Questions:

Are user-defined labels/annotations supported on VolSync CRs like ReplicationSource and ReplicationDestination?

If not, is there an alternative recommended approach to identify and selectively delete only a subset of VolSync resources (e.g., based on an owner or group)?

Could this be considered a feature request to support custom labels for better resource lifecycle management?

Thanks in advance for any guidance!
