### DISCUSSION TITLE
Multiple Types Of Triggers?

### DISCUSSION THREAD

**Discussion by dcplaya** [backube/volsync#576] [Q&A]
Can I have multiple types of triggers? For example

```
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: pvc
  namespace: default
spec:
  sourcePVC: config
  trigger:
    manual: initial
    schedule: "0 */2 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: pvc-restic
    cacheCapacity: 5Gi
    volumeSnapshotClassName: csi-rbdplugin-snapclass
    storageClassName: ceph-block
    retain:
      daily: 10
      within: 3d
```

It seems to accept the manual trigger and ignores the scheduled one. If I removed the manual one, the scheduled one works
