### ISSUE TITLE
Restic restore job not capturing errors with connecting to remote repository

### ISSUE THREAD

**Issue by tesshuflower** [backube/volsync#1004]
**Describe the bug**

In a ReplicationDestination using restic, the restic mover job to do the restore is not reporting errors if the RESTIC_REPOSITORY is not accessible.

The mover job ends up being successful, so no indication in the replicationdestination that the restore failed.

Example ReplicationDestination status after restore:

```
status:
  conditions:
  - lastTransitionTime: "2023-11-28T15:59:29Z"
    message: Waiting for manual trigger
    reason: WaitingForManual
    status: "False"
    type: Synchronizing
  lastManualSync: restore-once
  lastSyncDuration: 1m33.549925697s
  lastSyncTime: "2023-11-28T15:59:29Z"
  latestImage:
    apiGroup: ""
    kind: PersistentVolumeClaim
    name: data-dest
  latestMoverStatus:
    logs: Restic completed in 3s
    result: Successful
```

Example restic restore mover job log:

```
Starting container
VolSync restic container version: v0.8.0+264bd87
restore
restic 0.16.2 compiled with go1.20.11 on linux/amd64
Testing mandatory env variables
=== Starting restore ===
Fatal: unable to open config file: Stat: Get "http://doesnotexist.svc.cluster.local:9000/restic-e2e/?location=": dial tcp: lookup doesnotexist.svc.cluster.local: no such host
Is there a repository at the following location?
s3:http://doesnotexist.svc.cluster.local:9000/restic-e2e/testbucket
No eligible snapshots found
Restic completed in 3s
=== Done ===
```

**Steps to reproduce**

**Expected behavior**

**Actual results**

**Additional context**
