### ISSUE TITLE
Add rdiff-backup replication method

### ISSUE THREAD

**Issue by kyrofa** [backube/volsync#1029]
**Describe the feature you'd like to have.**
Support replication via [rdiff-backup](https://rdiff-backup.net). This is our current backup method, but as we move more products to k8s, it has gotten harder to pull off. We started investigating writing an operator to take a snapshot and use rdiff-backup, but then we discovered VolSync, which is almost a perfect fit except for this lack of support. Instead of building our own, I'd be happy to contribute this support to volsync, but I wanted to first log an issue and gauge interest.

**What is the value to the end user? (why is it a priority?)**
rdiff-backup is a reverse incremental backup tool that uses the rsync protocol. It's not really suitable for replication, to be clear, but a way to take space-efficient backups. It generally works over SSH.

**How will we know we have a good solution? (acceptance criteria)**
A new replication method that looks a bit like the current rsync SSH method, something like the following:

```yaml
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
# snip...
spec:
  # snip...
  rdiff-backup:
    sshKeys: volsync-rdiff-dest-sshkeys
    address: my.host.com
    copyMethod: Clone
```
