### ISSUE TITLE
Merge custom CA option into repository key.

### ISSUE THREAD

**Issue by blmhemu** [backube/volsync#1369]
**Describe the feature you'd like to have.**
Currently, we need to add another customCA field if usign self signed certs.
Usually users prefer to have all the secrets in one secret resource and uniformity when using them. 

**What is the value to the end user? (why is it a priority?)**
Simplified UX - Just add `RESTIC_CUSTOM_CA` field in secret and remove `customCA` field.

**How will we know we have a good solution? (acceptance criteria)**
Listed above.

**Additional context**
NA

**Comment by tesshuflower** [comment]
@blmhemu I think if the end goal is simply to use one secret, you can do this currently.

In the spec where you specify the secret, you can re-use the same secret where you store the rest of the restic config.

Say your restic secret (with keys such as `RESTIC_REPOSITORY` is called `restic-config`.

You could create a key in this `restic-config` secret that contains the contents of your ca.crt.  For this example I'll call this key `cacrtkey`.  Then you can use it in your replicationsource or replication destination like this:

```
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mydata-backup-with-customca
spec:
  restic:
    # Name of the Secret with the connection information
    repository: restic-config
    # ...
    customCA:
      secretName: restic-config
      key: cacrtkey
```
