### ISSUE TITLE
VolSync docs need some information about how to give non-admin users permissions

### ISSUE THREAD

**Issue by tesshuflower** [backube/volsync#161]
**Describe the bug**
This came from the Operate First team - they would like some more information in the docs to highlight user permissions needed to use VolSync.  

A suggestion was some sort of cookbook or guide to show an example.

**Steps to reproduce**

**Expected behavior**

**Actual results**

**Additional context**

**Comment by larsks** [comment]
When we initially deployed the operator, we were surprised to find that it wasn't immediately usable by project admins. We thought that should be called out in the documentation, along with example RBACs to enable someone to use it.

What we've done in our environment is create a clusterrole with `rbac.authorization.k8s.io/aggregate-to-admin: "true"`, making volsync usable by anyone with the `admin` role in the namespace. This seems like it would make a good example in the docs, but I wonder if it would also be a reasonable default to include in the volsync installation.

**Comment by JohnStrunk** [comment]
I poked around a bit to see if I could find the rbac yaml that you're using, but I was unsuccessful. :cry: 

I assume it's something like this:
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volsync-edit
  labels:
    # Grant access to namespace admins
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    # Grant access to namespace editors
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  # Give users full control of ReplicationSource and ReplicationDestination
  # objects so they can manage data replication
  - apiGroups: ["volsync.backube"]
    resources: ["replicationdestinations", "replicationsources"]
    verbs: ["create", "delete", "deletecollection", "patch", "update", "get,", "list", "watch"]
  - apiGroups: ["volsync.backube"]
    resources: ["replicationdestinations/status", "replicationsources/status"]
    verbs: ["get,", "list", "watch"]
  # Give users the ability to view VolumeSnapshots so they can "promote" the
  # destination snapshots into usable PVCs
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots", "volumesnapshots/status"]
    verbs: ["get,", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volsync-view
  labels:
    # Grant access to namespace viewers
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  # Give users read access to ReplicationSource and ReplicationDestination
  # objects so they can monitor data replication
  - apiGroups: ["volsync.backube"]
    resources: ["replicationdestinations", "replicationsources", "replicationdestinations/status", "replicationsources/status"]
    verbs: ["get,", "list", "watch"]
  # Give users the ability to monitor (destination) VolumeSnapshots
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots", "volumesnapshots/status"]
    verbs: ["get,", "list", "watch"]
```

...and today I got to learn about role aggregation :grin:
