### ISSUE TITLE
Condition Synchronizing only added after 1st sync

### ISSUE THREAD

**Issue by JohnStrunk** [backube/volsync#200]
**Describe the bug**
The Condition "Synchronizing" is only added to the `.status` after the 1st sync finishes. This makes it hard to tell what's going on during the initial sync iteration.

**Steps to reproduce**
Create an RS/RD and `kubectl get ...` it.

**Expected behavior**

**Actual results**
```yaml
  status:
    conditions:
    # No "type: Synchronizing" in the list
    - lastTransitionTime: "2022-04-18T15:56:54Z"
      message: Reconcile complete
      reason: ReconcileComplete
      status: "True"
      type: Reconciled
    lastSyncStartTime: "2022-04-18T15:56:52Z"
    rsync:
      address: 10.96.28.227
      sshKeys: volsync-rsync-dst-src-datavol
```

**Additional context**
I haven't looked yet, but I suspect this is due to only updating the condition on phase change (sync vs cleanup). We just need to add a check in there to add it if it's not present.
