### ISSUE TITLE
Support backing up to NFS/existing PVC using restic

### ISSUE THREAD

**Issue by onedr0p** [backube/volsync#319]
**Describe the feature you'd like to have.**

Support backing up to an PVC using restic

**What is the value to the end user? (why is it a priority?)**

Instead of object storage Restic could back up to an existing PVC (like one that is a NFS mount)

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volsync-nfs
spec:
  storageClassName: volsync-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "192.168.1.1"
    path: /tank/backups
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volsync-nfs
  namespace: home
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: volsync-nfs
  resources:
    requests:
      storage: 1Mi
```

Maybe you could add a option in the restic config, e.g.

```yaml
restic:
  # If `RESTIC_REPOSITORY` is a local path, backup to an existing PVC
  existingPVC: volsync-nfs
```

But maybe there's a better way to do this, like embedding the nfs options into the config?

```yaml
restic:
  # Back up to an NFS server
  nfs:
    server: 192.168.1.1
    path: /tank/backup/app
```

**How will we know we have a good solution? (acceptance criteria)**

- Back up to NFS Server and/or `existingClaim`

**Additional context**

**Comment by onedr0p** [comment]
While I can see `moverVolumes` was added it only accepts an existing claim or a secret. There is no option to use an inline nfs option.

Ideally it would be nice if this worked or something like it.

```yaml
    moverVolumes:
      - mountPath: /repo
        volumeSource:
          nfs:
            path: /mnt/eros/Media
            server: expanse.internal
```

The reason for this is that PVC is namespace scoped, and each namespace would need an exiting claim pointing to a NFS PV (see issue description)
