### ISSUE TITLE
Allow setting keep last on restic data mover

### ISSUE THREAD

**Issue by onedr0p** [backube/volsync#557]
**Describe the feature you'd like to have.**

According to the [Restic docs](https://restic.readthedocs.io/en/stable/060_forget.html#removing-snapshots-according-to-a-policy) there is a `--keep-last` which will keep the latest number of snapshots.

It would be nice if this was able to be used in a `ReplicationDestination`. e.g.

```yaml
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
   name: database-source
   namespace: source
spec:
   sourcePVC: mysql-pv-claim
   trigger:
      schedule: "*/30 * * * *"
   restic:
     pruneIntervalDays: 15
     repository: restic-config
     retain:
       # Last will only keep the last X number of snapshots
       last: 14
     copyMethod: Clone
```

**What is the value to the end user? (why is it a priority?)**

Allows backups to be retained on a number of snapshots level, not time based

**How will we know we have a good solution? (acceptance criteria)**

**Additional context**

**Comment by lltr** [comment]
Seems like the docs at https://volsync.readthedocs.io/_/downloads/en/latest/pdf/, page 107 shows an example of using `last` in a 
`ReplicationSource`, can I confirm if this issue is completed?

**Comment by onedr0p** [comment]
For now I am able to use `within` as a workaround.

```yaml
    retain:
      daily: 7
      within: 3d
```

This will keep all snapshots within 3 days and also 1 per day for up to 7 days.
