### ISSUE TITLE
Backup to a local NAS? Is this already possible?

### ISSUE THREAD

**Issue by Rojikku** [backube/volsync#563]
**Describe the feature you'd like to have.**
I would like to backup to my local NAS, ideally encrypted. S3 backups would generally be slower/more costly to restore from, and my NAS already has a "back up to cloud" feature, so it's more convenient to back up to the NAS and let it handle the rest.
My NAS supports SFTP, rsync, NFS, and other options. SFTP, in particular, is supported by both rclone and restic.

**What is the value to the end user? (why is it a priority?)**
Adds flexibility to backup options beyond just S3. Might only require some documentation updates? Or some more variables to pass things through.
Rclone supports SFTP, and Restic supports both SFTP and Rclone. A criteria for support is generally to be able to pass through the username, private key, and any other ssh config information, along with the port.

**How will we know we have a good solution? (acceptance criteria)**
Solving #431 would give me basic functionality, but simply adding ENV variables I can pass- or documenting them if they exist already- to allow me to specify the needed information for an SFTP would be more than adequate.

**Additional context**
N/A

**Comment by onedr0p** [comment]
Duplicate of https://github.com/backube/volsync/issues/319

**Comment by Rojikku** [comment]
> Duplicate of #319

Well, I saw #319, I'd consider this different since while you want to use existing PVCs/NFS, I just want to use existing features of rclone/restic.
But either one leads to the exact same end goal, yes.

**Comment by JohnStrunk** [comment]
I think sftp is probably the best bet for this use-case. We're working to deprecate the rsync-ssh mover in favor of rsync-tls (#370) due to the difficulties of running containerized sshd w/ minimal privileges.

Adding sftp support will require getting the ssh keys into the mover pod. Since both restic and rclone use a Secret for their configuration information, this shouldn't be too difficult to add. It'd likely be an optional field in the Secret that gets mounted to the mover and copied or linked into place.

**Comment by Rojikku** [comment]
Managed to successfully implement this using SFTP.
```
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: zwave-js-ui
  namespace: hass
spec:
  sourcePVC: zwave-pvc
  trigger:
    # Synchronize every 5 minutes
    schedule: "*/5 * * * *"
  rclone:
    rcloneConfigSection: "NAS"
    rcloneDestPath: "/k8s/hass/zwave"
    rcloneConfig: "rclone-conf"
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
```

Add a secret to each namespace with the config you want, and you're off to the races.
