### ISSUE TITLE
Pass annotations to Service objects

### ISSUE THREAD

**Issue by nesanton** [backube/volsync#596]
**Describe the feature you'd like to have.**
When defining the `ReplicationDestination` that defines a `serviceType`, I'd like to have an option of specifying annotations that would be passed to the Service object.
My use case: On Azure the services of type `LoadBalancer` can be annotated with `service.beta.kubernetes.io/azure-load-balancer-internal: "true"` which makes them private. By default such services are created with public (internet facing) scope.

**What is the value to the end user? (why is it a priority?)**
Right now there's no way to create internally scoped `LoadBalancer` services via the volsync operator. Unaware users may experience unexpected costs related to traffic passing out and in their cloud premise.

**How will we know we have a good solution? (acceptance criteria)**
Defining a `ReplicationDestination` for e.g. rsync type of replication with `serviceType: LoadBalancer` and a new additional field e.g. `serviceAnnotations: []` passes the annotations to the Service object. In case of Azure this results in creation of an internally scoped load balancer.

```yaml
spec:
  rsync:
    serviceType: LoadBalancer
    serviceAnnotations:
      - service.beta.kubernetes.io/azure-load-balancer-internal: "true"
```

**Additional context**
Kubernetes on Azure, OpenShift Container Platform on Azure, ARO
