### ISSUE TITLE
Restic backup never reaches Done even though Restic completed successfully

### ISSUE THREAD

**Issue by 0dragosh** [backube/volsync#788]
**Describe the bug**
Restic backup never reaches `=== Done ===` even though Restic completed successfully

**Steps to reproduce**
Take a restic backup

**Expected behavior**
finish the backup

**Actual results**
```
Starting container
VolSync restic container version: v0.7.1+8af0bf0
backup
restic 0.15.1 compiled with go1.19.7 on linux/amd64
Testing mandatory env variables
== Checking directory for content ===
== Initialize Dir =======
ID        Time                 Host        Tags        Paths
------------------------------------------------------------
88c570d9  2023-07-04 06:51:26  volsync                 /data
------------------------------------------------------------
1 snapshots
=== Starting backup ===
/data /
using parent snapshot 88c570d9

Files:           0 new,   271 changed,     0 unmodified
Dirs:            0 new,    15 changed,     0 unmodified
Added to the repository: 98.609 KiB (21.898 KiB stored)

processed 271 files, 19.028 MiB in 0:00
snapshot 58391a18 saved
/
=== Starting forget ===
Applying Policy: keep 10 daily snapshots and all snapshots within 10d of the newest
keep 2 snapshots:
ID        Time                 Host        Tags        Reasons         Paths
----------------------------------------------------------------------------
88c570d9  2023-07-04 06:51:26  volsync                 within 10d      /data
58391a18  2023-07-04 06:58:26  volsync                 within 10d      /data
                                                       daily snapshot
----------------------------------------------------------------------------
2 snapshots

Restic completed in 2s


```

**Additional context**
I have a few dozen restic backups, some of which fail like this with the pod stuck running because the restic backup never reaches the `Done` status. There is nothing special for the `RS`-es where it works vs where it doesn't. As a matter of fact I recreated them and pointed them to new restic repos and they seem random (some work some don't).

Example of a `ReplicationSource` where this happens:

```
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: calibre-web
  namespace: media
spec:
  sourcePVC: config-calibre-web-0
  trigger:
    schedule: "0 */12 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: calibre-web-restic-secret
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 14
```

**I would like to add that this is random new behavior, the exact same RS-es worked fine at one point and there were no changes made on any side.**
